### ISSUE TITLE
Default value of $epsilon

### ISSUE THREAD

**Issue by Vadskye** [belden/perl-test-easy#3]
Right now, the treatment of an unspecified $epsilon appears inconsistent. In around_about, it defaults to 0, but in nearly and nearly_ok, it is left uninitialized (and generates a warning when used). I can see three ways to resolve this:
1. $epsilon always silently defaults to 0. This is the most expected behavior, I think.
2. $epsilon always throws warnings when left unspecified. This is the most unambiguous behavior.
3. $epsilon defaults to some "reasonable" value based on the magnitude of $expected. The proportion and behavior can be specified as a customization option when importing the package. This is the most interesting and useful behavior, I think. It makes writing approximate tests very easy; rather than forcing testers to individually specify every $epsilon, they can simply specify a general $epsilon ratio which is good enough and focus on the rest of the test behavior.

I can implement any of these; which do you think suits the package best?

**Comment by belden** [comment]
> Which do you think Suits the package best?

I don't know :)

Can I ask you for a few example cases, where you can show:

- the weird interaction of the defaults (even if that weird interaction is cognitive)

- how those tests would change if we imagined that each of implementations #1, 2, and 3 were in place.

I'll be slow to reply for the next few days as I've lost my laptop, but I'll have a new one come 1/20 or 1/21.

(How did you find this project?)

**Comment by Vadskye** [comment]
Sorry for the delay in responding. It's been a crazy week...

Weird interaction of defaults:

Calling nearly_ok($actual, $expected) throws a "Use of uninitialized value $epsilon in numeric le (<=)" warning.
Calling around_about($now) does not throw any warnings.

The particular uninitialized warning generated here is particularly confusing because, from the perspective of the caller, it's not obvious what $epsilon is or why a numeric le is being used.

Tests would change in the following ways.

Under solution #1:
nearly_ok($actual, $expected) would succeed if $actual == $expected, and fail otherwise. This is the current test behavior; the only difference is that no warning would be generated.
around_about($now) would not change behavior.

Under solution #2:
nearly_ok($actual, $expected) would not change behavior. A more helpful error message would be created, but the testing itself would be unchanged.
around_about($now) would generate a warning, while previously it did not. It would not change testing behavior.

Under solution #3:
nearly_ok($actual, $expected) would fail if ($expected - $got <= $expected * $Test::Easy::Epsilonscale).
around_about($now) would fail if the time difference was greater than $Test::Easy::Defaulttimediff.

Does that help?

(I found this project through the CPAN Challenge - http://blogs.perl.org/users/neilb/2014/12/take-the-2015-cpan-pull-request-challenge.html)
