### ISSUE TITLE
Dependency Hash::MostUtils not installable for newer perls

### ISSUE THREAD

**Issue by eserte** [belden/perl-test-easy#4]
Test::Easy depends on Hash::MostUtils, which has only test failures for newer perls, see http://matrix.cpantesters.org/?dist=Hash-MostUtils . Is it possible to not use this dependency? Or to fix https://github.com/belden/perl-hash-mostutils/issues/1 (and probably other issues)?

**Comment by belden** [comment]
Thanks for reporting this! I've fixed belden/perl-hash-mostutils, and uploaded v1.07 to CPAN. That should fix this issue, but I'll leave this open until then.

**Comment by eserte** [comment]
Looks fine now.

**Comment by belden** [comment]
:+1: thanks!
